spring:
  application:
    name: delivery-management
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery
    username: postgres
    password: postgres